# Generated by Django 3.2.25 on 2024-10-24 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_app', '0003_kanat_uretim_tarihi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviyonik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucak_adi', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('Akıncı', 'Akıncı'), ('Kızılelma', 'Kızılelma')], max_length=50)),
                ('aviyonik_seri_numarasi', models.CharField(blank=True, max_length=100)),
                ('uretim_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Govde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucak_adi', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('Akıncı', 'Akıncı'), ('Kızılelma', 'Kızılelma')], max_length=50)),
                ('govde_seri_numarasi', models.CharField(blank=True, max_length=100)),
                ('uretim_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Kuyruk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucak_adi', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('Akıncı', 'Akıncı'), ('Kızılelma', 'Kızılelma')], max_length=50)),
                ('kuyruk_seri_numarasi', models.CharField(blank=True, max_length=100)),
                ('uretim_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
