# Generated by Django 3.2.25 on 2024-10-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_app', '0004_aviyonik_govde_kuyruk'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanat',
            name='status',
            field=models.CharField(choices=[('uygun', 'Uygun'), ('kullanimda', 'Kullanımda')], default='uygun', max_length=20),
        ),
    ]
