# Generated by Django 3.2.25 on 2024-10-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_app', '0005_kanat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviyonik',
            name='status',
            field=models.CharField(choices=[('uygun', 'Uygun'), ('kullanimda', 'Kullanımda')], default='uygun', max_length=20),
        ),
        migrations.AddField(
            model_name='govde',
            name='status',
            field=models.CharField(choices=[('uygun', 'Uygun'), ('kullanimda', 'Kullanımda')], default='uygun', max_length=20),
        ),
        migrations.AddField(
            model_name='kuyruk',
            name='status',
            field=models.CharField(choices=[('uygun', 'Uygun'), ('kullanimda', 'Kullanımda')], default='uygun', max_length=20),
        ),
    ]
