# Generated by Django 3.2.25 on 2024-10-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_app', '0008_auto_20241024_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucak',
            name='aviyonik_serial',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ucak',
            name='govde_serial',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ucak',
            name='kanat_serial',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ucak',
            name='kuyruk_serial',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ucak',
            name='seri_numarasi',
            field=models.CharField(max_length=100),
        ),
    ]
